version: '3.7'

services:
    pgdb:
        container_name: pg_container
        image: 'postgres:13'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: testdb
        volumes:
            - pgdb-data:/var/lib/postgresql/data
        ports:
            - '127.0.0.1:5432:5432'

    pgadmin:
        container_name: pgadmin4_container
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: VERYlongPASSWORD
        ports:
            - '127.0.0.1:5050:80'
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        links:
            - 'pgdb:pgsql-server'

volumes:
    pgdb-data:
    pgadmin-data:
